/*
 * Copyright 2025 Ron Lauren Hombre
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *        and included as LICENSE.txt in this Project.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package asia.hombre.kyber

import kotlin.jvm.JvmName

/**
 * A class for ML-KEM Encapsulation Results.
 *
 * This class contains the Shared Secret Key and the Cipher Text.
 *
 * @constructor Stores the Shared Secret Key and the Cipher Text.
 * @author Ron Lauren Hombre
 */
class KyberEncapsulationResult internal constructor(
    private val sharedSecretKey_: ByteArray,
    private val cipherText_: KyberCipherText
) {
    /**
     * The Shared Secret Key generated by the Encapsulation.
     *
     * @return [ByteArray] - 32 Bytes.
     */
    @get:JvmName("getSharedSecretKey")
    val sharedSecretKey: ByteArray
        get() = sharedSecretKey_.copyOf()

    /**
     * The Shared Secret Key generated by the Encapsulation.
     *
     * @return [ByteArray] - 32 Bytes.
     */
    @get:JvmName("getSecretKey")
    @Deprecated("This method name does not match the term in NIST FIPS 203.", level = DeprecationLevel.WARNING,
        replaceWith = ReplaceWith("sharedSecretKey")
    )
    val secretKey: ByteArray
        get() = sharedSecretKey

    /**
     * The [KyberCipherText] generated by the Encapsulation.
     *
     * @return [KyberCipherText]
     */
    @get:JvmName("getCipherText")
    val cipherText: KyberCipherText
        get() = cipherText_.copy()
}